package struple;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import struple.Json.JsonObject;
import struple.Struple.Element;
import struple.Struple.Packer;
import struple.Struple.Reader;

/**
 * Drives the Java implementation against the language-neutral contract in
 * {@code conformance/vectors.json} (generated by the Zig reference) and
 * {@code conformance/semantic_vectors.json}. Every vector must reproduce in both directions.
 *
 * <p>Two entry shapes:
 *
 * <pre>
 *   {json, bytes}  -- fromJson(json) == bytes  and  toJson(bytes) == json
 *   {build, bytes} -- encode(build(op)) == bytes  and  transcode(bytes) == bytes
 * </pre>
 *
 * <p>CWD must be {@code java/} so the corpus resolves at {@code ../conformance/*.json}.
 */
public final class TestConformance {

    private static int failures = 0;

    public static void main(String[] args) throws Exception {
        String corpus = read("../conformance/vectors.json");
        Object rootObj = Json.parse(corpus);
        @SuppressWarnings("unchecked")
        List<Object> vectors = (List<Object>) rootObj;

        int jsonEnc = 0;
        int jsonDec = 0;
        int buildEnc = 0;
        int buildTrc = 0;

        for (Object o : vectors) {
            JsonObject v = (JsonObject) o;
            String want = (String) v.get("bytes");
            byte[] bin = hexDecode(want);

            if (v.has("json")) {
                String json = (String) v.get("json");
                // encode: fromJson(json) == bytes
                String got = hexEncode(Json.fromJson(json));
                expectEq("json-encode [" + json + "]", got, want);
                jsonEnc++;
                // decode: toJson(bytes) == json
                String back = Json.toJson(bin);
                expectEq("json-decode [" + json + "]", back, json);
                jsonDec++;
            } else if (v.has("build")) {
                Object op = v.get("build");
                // encode: encode(build(op)) == bytes
                Packer w = new Packer();
                buildInto(w, op);
                expectEq("build [" + want + "]", hexEncode(w.bytes()), want);
                buildEnc++;
                // transcode: transcode(bytes) == bytes
                expectEq("transcode [" + want + "]", hexEncode(transcode(bin)), want);
                buildTrc++;
            }
        }

        // semantic-order corpus
        int semOk = 0;
        String semCorpus = read("../conformance/semantic_vectors.json");
        @SuppressWarnings("unchecked")
        List<Object> semVectors = (List<Object>) Json.parse(semCorpus);
        for (Object o : semVectors) {
            JsonObject pr = (JsonObject) o;
            byte[] a = hexDecode((String) pr.get("a"));
            byte[] b = hexDecode((String) pr.get("b"));
            int wantOrder = ((BigInteger) pr.get("order")).intValueExact();
            int got = Semantic.semanticOrder(a, b);
            if (got != wantOrder) {
                System.err.println("SEMANTIC FAIL " + pr.get("a") + " <=> " + pr.get("b")
                        + ": got " + got + " want " + wantOrder);
                failures++;
            } else {
                semOk++;
            }
        }

        // malformed / hostile corpus — every case must reject with the port's own clean decode
        // error (StrupleException). A different exception type (IllegalArgumentException,
        // ArrayIndexOutOfBoundsException, ...) or no throw at all is a hardening FAILURE.
        int malformedTotal = 0;
        int malformedRejected = 0;
        String malCorpus = read("../conformance/malformed.json");
        JsonObject malRoot = (JsonObject) Json.parse(malCorpus);
        @SuppressWarnings("unchecked")
        List<Object> malCases = (List<Object>) malRoot.get("cases");
        for (Object o : malCases) {
            JsonObject c = (JsonObject) o;
            String hex = (String) c.get("hex");
            byte[] bin = hexDecode(hex);
            malformedTotal++;
            try {
                transcode(bin); // fully walk the stream: decode + re-encode every element
                System.err.println("MALFORMED FAIL [" + hex + "]: accepted, should reject — "
                        + c.get("note"));
                failures++;
            } catch (Struple.StrupleException ok) {
                malformedRejected++; // the port's clean decode error — the only acceptable outcome
            } catch (RuntimeException wrong) {
                System.err.println("MALFORMED FAIL [" + hex + "]: wrong exception type "
                        + wrong.getClass().getName() + ": " + wrong.getMessage());
                failures++;
            }
        }

        System.out.printf(
                "TestConformance: json encode %d decode %d | build %d transcode %d | semantic %d "
                        + "| malformed %d/%d rejected | %d failures%n",
                jsonEnc, jsonDec, buildEnc, buildTrc, semOk, malformedRejected, malformedTotal,
                failures);
        if (failures != 0) {
            System.exit(1);
        }
    }

    // -----------------------------------------------------------------------
    // Build-op interpreter — mirrors the Zig generator and the other ports.
    // -----------------------------------------------------------------------

    private static void buildInto(Packer w, Object opObj) {
        JsonObject op = (JsonObject) opObj;
        String key = op.keys.get(0);
        Object val = op.values.get(0);
        switch (key) {
            case "nil":
                w.appendNil();
                break;
            case "undef":
                w.appendUndefined();
                break;
            case "bool":
                w.appendBool((Boolean) val);
                break;
            case "int":
                w.appendBigInteger(new BigInteger((String) val));
                break;
            case "float64":
                w.appendFloat64(asDouble(val));
                break;
            case "float32":
                w.appendFloat32((float) asDouble(val));
                break;
            case "timestamp":
                w.appendTimestamp(Long.parseLong((String) val));
                break;
            case "uuid":
                w.appendUuid(hexDecode((String) val));
                break;
            case "decimal":
                w.appendDecimalString((String) val);
                break;
            case "string":
                w.appendString((String) val);
                break;
            case "bytes":
                w.appendBytes(hexDecode((String) val));
                break;
            case "array": {
                Packer child = new Packer();
                for (Object item : asList(val)) {
                    buildInto(child, item);
                }
                w.appendArray(child.bytes());
                break;
            }
            case "set": {
                List<byte[]> elems = new ArrayList<>();
                for (Object item : asList(val)) {
                    elems.add(buildOne(item));
                }
                w.appendSet(elems);
                break;
            }
            case "map": {
                List<byte[][]> entries = new ArrayList<>();
                for (Object pairObj : asList(val)) {
                    List<Object> pair = asList(pairObj);
                    entries.add(new byte[][] {buildOne(pair.get(0)), buildOne(pair.get(1))});
                }
                w.appendMap(entries);
                break;
            }
            default:
                throw new RuntimeException("unknown op " + key);
        }
    }

    private static byte[] buildOne(Object op) {
        Packer w = new Packer();
        buildInto(w, op);
        return w.bytes();
    }

    @SuppressWarnings("unchecked")
    private static List<Object> asList(Object o) {
        return (List<Object>) o;
    }

    private static double asDouble(Object val) {
        if (val instanceof Double d) {
            return d;
        }
        if (val instanceof BigInteger i) {
            return i.doubleValue();
        }
        return 0.0;
    }

    // -----------------------------------------------------------------------
    // transcode: decode every element and re-encode it (decoder round-trip).
    // -----------------------------------------------------------------------

    static byte[] transcode(byte[] data) {
        Reader r = new Reader(data);
        Packer out = new Packer();
        Element e;
        while ((e = r.next()) != null) {
            appendElement(out, e);
        }
        return out.bytes();
    }

    private static void appendElement(Packer out, Element e) {
        switch (e.kind) {
            case NIL:
                out.appendNil();
                break;
            case UNDEF:
                out.appendUndefined();
                break;
            case BOOLEAN:
                out.appendBool(e.boolValue());
                break;
            case INT:
            case BIG_INT:
                out.appendBigInteger(e.intValue());
                break;
            case FLOAT32:
                out.appendFloat32(e.float32());
                break;
            case FLOAT64:
                out.appendFloat64(e.float64());
                break;
            case DECIMAL: {
                Struple.Decimal d = e.decimal();
                out.appendDecimal(d.negative, d.coefficientDigits(), (int) d.exponent());
                break;
            }
            case TIMESTAMP:
                out.appendTimestamp(e.timestamp());
                break;
            case UUID:
                out.appendUuid(e.uuid());
                break;
            case STRING:
                out.appendStringBytes(e.stringBytes());
                break;
            case BYTES:
                out.appendBytes(e.bytesValue());
                break;
            case ARRAY:
                out.appendContainerBody(Struple.ARRAY, e.inner());
                break;
            case MAP:
                out.appendContainerBody(Struple.MAP, e.inner());
                break;
            case SET:
                out.appendContainerBody(Struple.SET, e.inner());
                break;
            default:
                throw new IllegalStateException();
        }
    }

    // -----------------------------------------------------------------------
    // hex / file helpers
    // -----------------------------------------------------------------------

    private static String read(String path) throws Exception {
        return new String(Files.readAllBytes(Paths.get(path)), StandardCharsets.UTF_8);
    }

    private static byte[] hexDecode(String hex) {
        int n = hex.length() / 2;
        byte[] b = new byte[n];
        for (int i = 0; i < n; i++) {
            b[i] = (byte) Integer.parseInt(hex.substring(i * 2, i * 2 + 2), 16);
        }
        return b;
    }

    private static String hexEncode(byte[] data) {
        StringBuilder sb = new StringBuilder(data.length * 2);
        for (byte x : data) {
            sb.append(Character.forDigit((x >> 4) & 0xF, 16));
            sb.append(Character.forDigit(x & 0xF, 16));
        }
        return sb.toString();
    }

    private static void expectEq(String label, String got, String want) {
        if (!got.equals(want)) {
            System.err.println("FAIL " + label + ": got " + got + " want " + want);
            failures++;
        }
    }

    private TestConformance() {}
}
