/* Drives the C implementation against the language-neutral contract in
 * conformance/vectors.json (generated by the Zig reference). Every vector must
 * reproduce in both directions. */
#include "struple.h"
#include "struple_json.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int failures = 0;

static char *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "cannot open %s\n", path);
        exit(2);
    }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = (char *)malloc((size_t)sz + 1);
    if (fread(buf, 1, (size_t)sz, f) != (size_t)sz) {
        fprintf(stderr, "read error\n");
        exit(2);
    }
    buf[sz] = 0;
    fclose(f);
    *out_len = (size_t)sz;
    return buf;
}

static char *hexenc(const uint8_t *data, size_t len) {
    char *s = (char *)malloc(len * 2 + 1);
    for (size_t i = 0; i < len; i++) sprintf(s + i * 2, "%02x", data[i]);
    s[len * 2] = 0;
    return s;
}

static void hexdec(const char *hex, uint8_t **out, size_t *out_len) {
    size_t n = strlen(hex) / 2;
    uint8_t *b = (uint8_t *)malloc(n ? n : 1);
    for (size_t i = 0; i < n; i++) {
        char t[3] = {hex[i * 2], hex[i * 2 + 1], 0};
        b[i] = (uint8_t)strtol(t, NULL, 16);
    }
    *out = b;
    *out_len = n;
}

static const sj_value *obj_get(const sj_value *obj, const char *key) {
    for (size_t i = 0; i < obj->pairs; i++)
        if (strcmp(obj->keys[i], key) == 0) return &obj->vals[i];
    return NULL;
}

static double sj_as_f64(const sj_value *v) {
    return v->kind == SJ_FLOAT ? v->float_val : strtod(v->str, NULL);
}

/* Interpret a build op into encoded bytes — mirrors the Zig generator and the
 * TS/Python/Rust conformance tests. */
static void build_into(struple_writer *w, const sj_value *op) {
    const char *key = op->keys[0];
    const sj_value *val = &op->vals[0];
    if (strcmp(key, "nil") == 0) {
        struple_append_nil(w);
    } else if (strcmp(key, "undef") == 0) {
        struple_append_undefined(w);
    } else if (strcmp(key, "bool") == 0) {
        struple_append_bool(w, val->bool_val);
    } else if (strcmp(key, "int") == 0) {
        struple_append_int(w, strtoll(val->str, NULL, 10));
    } else if (strcmp(key, "float64") == 0) {
        struple_append_f64(w, sj_as_f64(val));
    } else if (strcmp(key, "float32") == 0) {
        struple_append_f32(w, (float)sj_as_f64(val));
    } else if (strcmp(key, "timestamp") == 0) {
        struple_append_timestamp(w, strtoll(val->str, NULL, 10));
    } else if (strcmp(key, "string") == 0) {
        struple_append_string(w, val->str, strlen(val->str));
    } else if (strcmp(key, "bytes") == 0) {
        uint8_t *b;
        size_t bl;
        hexdec(val->str, &b, &bl);
        struple_append_bytes(w, b, bl);
        free(b);
    } else if (strcmp(key, "array") == 0) {
        struple_writer child;
        struple_writer_init(&child);
        for (size_t i = 0; i < val->count; i++) build_into(&child, &val->items[i]);
        struple_append_array(w, child.data, child.len);
        struple_writer_free(&child);
    } else if (strcmp(key, "set") == 0) {
        size_t n = val->count;
        struple_writer *ews = (struple_writer *)calloc(n ? n : 1, sizeof(struple_writer));
        struple_bytes *elems = (struple_bytes *)malloc((n ? n : 1) * sizeof(struple_bytes));
        for (size_t i = 0; i < n; i++) {
            struple_writer_init(&ews[i]);
            build_into(&ews[i], &val->items[i]);
            elems[i].ptr = ews[i].data;
            elems[i].len = ews[i].len;
        }
        struple_append_set(w, elems, n);
        for (size_t i = 0; i < n; i++) struple_writer_free(&ews[i]);
        free(ews);
        free(elems);
    } else if (strcmp(key, "map") == 0) {
        size_t n = val->count;
        struple_writer *kws = (struple_writer *)calloc(n ? n : 1, sizeof(struple_writer));
        struple_writer *vws = (struple_writer *)calloc(n ? n : 1, sizeof(struple_writer));
        struple_kv *entries = (struple_kv *)malloc((n ? n : 1) * sizeof(struple_kv));
        for (size_t i = 0; i < n; i++) {
            const sj_value *pair = &val->items[i];
            struple_writer_init(&kws[i]);
            build_into(&kws[i], &pair->items[0]);
            struple_writer_init(&vws[i]);
            build_into(&vws[i], &pair->items[1]);
            entries[i].key.ptr = kws[i].data;
            entries[i].key.len = kws[i].len;
            entries[i].value.ptr = vws[i].data;
            entries[i].value.len = vws[i].len;
        }
        struple_append_map(w, entries, n);
        for (size_t i = 0; i < n; i++) {
            struple_writer_free(&kws[i]);
            struple_writer_free(&vws[i]);
        }
        free(kws);
        free(vws);
        free(entries);
    } else {
        fprintf(stderr, "unknown op %s\n", key);
        exit(1);
    }
}

static void expect_hex(const char *label, const uint8_t *got, size_t got_len, const char *want) {
    char *h = hexenc(got, got_len);
    if (strcmp(h, want) != 0) {
        fprintf(stderr, "FAIL %s: got %s want %s\n", label, h, want);
        failures++;
    }
    free(h);
}

int main(void) {
    size_t flen;
    char *text = read_file("../conformance/vectors.json", &flen);
    sj_value *root = struple_json_parse(text, flen);
    if (!root || root->kind != SJ_ARRAY) {
        fprintf(stderr, "could not parse corpus\n");
        return 2;
    }

    int json_enc = 0, json_dec = 0, build_enc = 0, build_trc = 0;
    for (size_t i = 0; i < root->count; i++) {
        const sj_value *v = &root->items[i];
        const char *want = obj_get(v, "bytes")->str;
        const sj_value *json = obj_get(v, "json");
        const sj_value *build = obj_get(v, "build");

        uint8_t *bin;
        size_t blen;
        hexdec(want, &bin, &blen);

        if (json) {
            struple_writer w;
            struple_writer_init(&w);
            struple_from_json(json->str, strlen(json->str), &w);
            expect_hex(json->str, w.data, w.len, want);
            json_enc++;
            struple_writer_free(&w);

            struple_writer jw;
            struple_writer_init(&jw);
            struple_to_json(bin, blen, &jw);
            if (jw.len != strlen(json->str) || memcmp(jw.data, json->str, jw.len) != 0) {
                fprintf(stderr, "DECODE FAIL: want %s got %.*s\n", json->str, (int)jw.len, jw.data);
                failures++;
            }
            json_dec++;
            struple_writer_free(&jw);
        } else if (build) {
            struple_writer w;
            struple_writer_init(&w);
            build_into(&w, build);
            expect_hex("build", w.data, w.len, want);
            build_enc++;
            struple_writer_free(&w);

            struple_writer tw;
            struple_writer_init(&tw);
            struple_transcode(bin, blen, &tw);
            expect_hex("transcode", tw.data, tw.len, want);
            build_trc++;
            struple_writer_free(&tw);
        }
        free(bin);
    }

    struple_json_free(root);
    free(text);
    printf("test_conformance: json encode %d decode %d | build %d transcode %d | %d failures\n",
           json_enc, json_dec, build_enc, build_trc, failures);
    return failures ? 1 : 0;
}
