//! Drives the Rust implementation against the language-neutral contract in
//! conformance/vectors.json (generated by the Zig reference). Every vector must
//! reproduce in both directions.
//!
//! Two entry shapes:
//!   {json, bytes}  — from_json(json) == bytes  and  to_json(bytes) == json
//!   {build, bytes} — encode(build(op)) == bytes and transcode(bytes) == bytes

use std::fs;
use struple::json::{from_json, parse, to_json, Json};
use struple::{transcode, unpack, Writer};

fn corpus() -> Vec<Json> {
    let path = format!("{}/../conformance/vectors.json", env!("CARGO_MANIFEST_DIR"));
    let text = fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    match parse(&text).expect("parse corpus") {
        Json::Array(v) => v,
        _ => panic!("corpus is not an array"),
    }
}

fn field<'a>(obj: &'a Json, key: &str) -> Option<&'a Json> {
    match obj {
        Json::Object(entries) => entries.iter().find(|(k, _)| k == key).map(|(_, v)| v),
        _ => None,
    }
}

fn as_str(j: &Json) -> &str {
    match j {
        Json::Str(s) => s,
        _ => panic!("expected string"),
    }
}

fn to_hex(bytes: &[u8]) -> String {
    let mut s = String::new();
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

fn from_hex(hex: &str) -> Vec<u8> {
    (0..hex.len() / 2).map(|i| u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).unwrap()).collect()
}

// Interpret a build op into encoded bytes — mirrors the Zig generator and the
// TypeScript/Python conformance tests.
fn build_one(op: &Json) -> Vec<u8> {
    let mut w = Writer::new();
    build_into(&mut w, op);
    w.into_bytes()
}

fn build_into(w: &mut Writer, op: &Json) {
    let entries = match op {
        Json::Object(e) => e,
        _ => panic!("op must be an object"),
    };
    let (key, val) = &entries[0];
    match key.as_str() {
        "nil" => {
            w.append_nil();
        }
        "undef" => {
            w.append_undefined();
        }
        "bool" => {
            w.append_bool(matches!(val, Json::Bool(true)));
        }
        "int" => {
            w.append_int(as_str(val).parse().unwrap());
        }
        "float64" => {
            w.append_f64(as_f64(val));
        }
        "float32" => {
            w.append_f32(as_f64(val) as f32);
        }
        "decimal" => {
            w.append_decimal_string(as_str(val)).unwrap();
        }
        "timestamp" => {
            w.append_timestamp(as_str(val).parse().unwrap());
        }
        "string" => {
            w.append_string(as_str(val));
        }
        "bytes" => {
            w.append_bytes(&from_hex(as_str(val)));
        }
        "uuid" => {
            let raw: [u8; 16] = from_hex(as_str(val)).try_into().unwrap();
            w.append_uuid(raw);
        }
        "array" => {
            let mut child = Writer::new();
            for o in as_array(val) {
                build_into(&mut child, o);
            }
            w.append_array(child.bytes());
        }
        "set" => {
            let elems: Vec<Vec<u8>> = as_array(val).iter().map(build_one).collect();
            w.append_set(&elems);
        }
        "map" => {
            let entries: Vec<(Vec<u8>, Vec<u8>)> = as_array(val)
                .iter()
                .map(|pair| {
                    let kv = as_array(pair);
                    (build_one(&kv[0]), build_one(&kv[1]))
                })
                .collect();
            w.append_map(&entries);
        }
        other => panic!("unknown op `{other}`"),
    }
}

fn as_array(j: &Json) -> &[Json] {
    match j {
        Json::Array(v) => v,
        _ => panic!("expected array"),
    }
}

fn as_f64(j: &Json) -> f64 {
    match j {
        Json::Float(f) => *f,
        Json::Int(i) => *i as f64,
        _ => panic!("expected number"),
    }
}

#[test]
fn corpus_has_vectors() {
    assert!(!corpus().is_empty());
}

#[test]
fn json_encode() {
    for v in corpus() {
        if let Some(j) = field(&v, "json") {
            let bytes = as_str(field(&v, "bytes").unwrap());
            assert_eq!(to_hex(&from_json(as_str(j)).unwrap()), bytes, "encode {}", as_str(j));
        }
    }
}

#[test]
fn json_decode() {
    for v in corpus() {
        if let Some(j) = field(&v, "json") {
            let bytes = as_str(field(&v, "bytes").unwrap());
            assert_eq!(to_json(&from_hex(bytes)).unwrap(), as_str(j), "decode {}", as_str(j));
        }
    }
}

#[test]
fn build_encode() {
    for v in corpus() {
        if let Some(op) = field(&v, "build") {
            let bytes = as_str(field(&v, "bytes").unwrap());
            assert_eq!(to_hex(&build_one(op)), bytes, "build {op:?}");
        }
    }
}

#[test]
fn build_transcode() {
    for v in corpus() {
        if field(&v, "build").is_some() {
            let bytes = as_str(field(&v, "bytes").unwrap());
            assert_eq!(to_hex(&transcode(&from_hex(bytes)).unwrap()), bytes, "transcode {bytes}");
        }
    }
}

// Build vectors may carry a one-way `to_json` field pinning the canonical JSON
// rendering (plain + scientific decimal notation) cross-language (Item 2). Where
// present, assert `to_json(bytes) == to_json`.
#[test]
fn build_to_json() {
    let mut checked = 0usize;
    for v in corpus() {
        if field(&v, "build").is_none() {
            continue;
        }
        if let Some(want) = field(&v, "to_json") {
            let bytes = from_hex(as_str(field(&v, "bytes").unwrap()));
            assert_eq!(&to_json(&bytes).unwrap(), as_str(want), "to_json {}", to_hex(&bytes));
            checked += 1;
        }
    }
    assert!(checked > 0, "no build vectors carried a `to_json` field");
    println!("build to_json: {checked} vectors checked");
}

/// Negative counterpart to the encode-only corpus: every entry in
/// conformance/malformed.json is a hostile encoding that a valid encoder cannot
/// produce, and the decoder MUST reject it cleanly — never a panic, OOB read, or
/// `Ok(value)`. Each case is fully decoded (recursively, via `unpack`, which
/// walks nested containers) and also transcoded, so every element is forced to be
/// read; both paths must return `Err`.
#[test]
fn malformed_rejected() {
    let path = format!("{}/../conformance/malformed.json", env!("CARGO_MANIFEST_DIR"));
    let text = fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let doc = parse(&text).expect("parse malformed corpus");
    let cases = match field(&doc, "cases") {
        Some(Json::Array(v)) => v,
        _ => panic!("malformed corpus has no `cases` array"),
    };
    assert!(!cases.is_empty(), "malformed corpus is empty");

    let total = cases.len();
    let mut rejected = 0usize;
    for c in cases {
        let hex = as_str(field(c, "hex").unwrap());
        let note = field(c, "note").map(as_str).unwrap_or("");
        let bytes = from_hex(hex);
        // Force reads of the whole stream on both decode paths.
        let unpacked = unpack(&bytes);
        let transcoded = transcode(&bytes);
        assert!(unpacked.is_err(), "NOT rejected by unpack: hex={hex} note=\"{note}\" got={unpacked:?}");
        assert!(transcoded.is_err(), "NOT rejected by transcode: hex={hex} note=\"{note}\" got={transcoded:?}");
        rejected += 1;
    }
    println!("malformed: {rejected}/{total} rejected");
    assert_eq!(rejected, total, "some malformed cases were not cleanly rejected");
}

#[test]
fn semantic_corpus() {
    use std::cmp::Ordering;
    let path = format!("{}/../conformance/semantic_vectors.json", env!("CARGO_MANIFEST_DIR"));
    let text = fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let pairs = match parse(&text).expect("parse semantic corpus") {
        Json::Array(v) => v,
        _ => panic!("semantic corpus is not an array"),
    };
    for pr in pairs {
        let (a_hex, b_hex) = (as_str(field(&pr, "a").unwrap()), as_str(field(&pr, "b").unwrap()));
        let want = match field(&pr, "order").unwrap() {
            Json::Int(i) => *i,
            _ => panic!("order is not an integer"),
        };
        let got: i128 = match struple::semantic_order(&from_hex(a_hex), &from_hex(b_hex)).unwrap() {
            Ordering::Less => -1,
            Ordering::Equal => 0,
            Ordering::Greater => 1,
        };
        assert_eq!(got, want, "semantic {a_hex} <=> {b_hex}");
    }
}
