// Drives the TypeScript implementation against the language-neutral contract in
// conformance/vectors.json (generated by the Zig reference). Every vector must
// reproduce in both directions.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { fromJson, toJson } from "../src/index.ts";

const here = dirname(fileURLToPath(import.meta.url));
const corpusPath = join(here, "..", "..", "conformance", "vectors.json");
const vectors = JSON.parse(readFileSync(corpusPath, "utf8")) as Array<{ json: string; bytes: string }>;

function toHex(bytes: Uint8Array): string {
  let s = "";
  for (const b of bytes) s += b.toString(16).padStart(2, "0");
  return s;
}

function fromHex(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

test(`corpus has vectors`, () => {
  assert.ok(vectors.length > 0);
});

for (const v of vectors) {
  test(`encode  ${v.json}`, () => {
    assert.equal(toHex(fromJson(v.json)), v.bytes, "fromJson(json) must equal corpus bytes");
  });
  test(`decode  ${v.json}`, () => {
    assert.equal(toJson(fromHex(v.bytes)), v.json, "toJson(bytes) must equal corpus json");
  });
}
