// Drives the TypeScript implementation against the language-neutral contract in
// conformance/vectors.json (generated by the Zig reference). Every vector must
// reproduce in both directions.
//
// Two entry shapes:
//   { json, bytes }  — fromJson(json) == bytes  and  toJson(bytes) == json
//   { build, bytes } — encode(build(op)) == bytes and transcode(bytes) == bytes

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { Writer, Reader, transcode, fromJson, toJson, semanticOrder } from "../src/index.ts";

const here = dirname(fileURLToPath(import.meta.url));
const corpusPath = join(here, "..", "..", "conformance", "vectors.json");
type Vector = { json?: string; build?: any; bytes: string; to_json?: string };
const vectors = JSON.parse(readFileSync(corpusPath, "utf8")) as Vector[];

const semanticPath = join(here, "..", "..", "conformance", "semantic_vectors.json");
type SemVector = { a: string; b: string; order: number };
const semVectors = JSON.parse(readFileSync(semanticPath, "utf8")) as SemVector[];

const malformedPath = join(here, "..", "..", "conformance", "malformed.json");
type MalformedCase = { hex: string; item: number; note: string };
const malformed = (JSON.parse(readFileSync(malformedPath, "utf8")) as { cases: MalformedCase[] }).cases;

function toHex(bytes: Uint8Array): string {
  let s = "";
  for (const b of bytes) s += b.toString(16).padStart(2, "0");
  return s;
}

function fromHex(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

// Interpret a build op into encoded bytes — mirrors the Zig generator and the
// Python conformance test.
function buildBytes(op: any): Uint8Array {
  const w = new Writer();
  buildInto(w, op);
  return w.bytes();
}

function buildInto(w: Writer, op: any): void {
  const key = Object.keys(op)[0];
  const val = op[key];
  switch (key) {
    case "nil": w.appendNil(); break;
    case "undef": w.appendUndefined(); break;
    case "bool": w.appendBool(val); break;
    case "int": w.appendInt(BigInt(val)); break;
    case "float64": w.appendFloat64(val); break;
    case "float32": w.appendFloat32(val); break;
    case "decimal": w.appendDecimalString(val); break;
    case "timestamp": w.appendTimestamp(BigInt(val)); break;
    case "uuid": w.appendUuid(fromHex(val)); break;
    case "string": w.appendString(val); break;
    case "bytes": w.appendBytes(fromHex(val)); break;
    case "array": {
      const child = new Writer();
      for (const o of val) buildInto(child, o);
      w.appendArray(child.bytes());
      break;
    }
    case "set": w.appendSet(val.map(buildOne)); break;
    case "map": w.appendMap(val.map((pair: any) => [buildOne(pair[0]), buildOne(pair[1])])); break;
    default: throw new Error(`unknown op ${key}`);
  }
}

function buildOne(op: any): Uint8Array {
  const w = new Writer();
  buildInto(w, op);
  return w.bytes();
}

test("corpus has vectors", () => assert.ok(vectors.length > 0));

for (const v of vectors) {
  const label = v.json ?? JSON.stringify(v.build);
  if (v.json !== undefined) {
    test(`encode  ${label}`, () => assert.equal(toHex(fromJson(v.json!)), v.bytes));
    test(`decode  ${label}`, () => assert.equal(toJson(fromHex(v.bytes)), v.json));
  } else {
    test(`build   ${label}`, () => assert.equal(toHex(buildBytes(v.build)), v.bytes));
    test(`transcode ${label}`, () => assert.equal(toHex(transcode(fromHex(v.bytes))), v.bytes));
    // Build vectors that carry a one-way `to_json` field additionally pin the
    // plain + scientific decimal rendering cross-language (Item 2).
    if (v.to_json !== undefined) {
      test(`to_json ${label}`, () => assert.equal(toJson(fromHex(v.bytes)), v.to_json));
    }
  }
}

const sgn = (n: number) => (n < 0 ? -1 : n > 0 ? 1 : 0);
for (const [i, sv] of semVectors.entries()) {
  test(`semantic ${i}: ${sv.a} <=> ${sv.b}`, () =>
    assert.equal(sgn(semanticOrder(fromHex(sv.a), fromHex(sv.b))), sv.order));
}

// Negative corpus: every hostile encoding must be REJECTED with a clean decode
// error. Fully drive the decoder over the whole stream (walk every element via
// the Reader, then transcode) — a malformed input must throw an Error, never
// return a wrong value and never crash with a non-Error.
function walkAll(bytes: Uint8Array): void {
  const r = new Reader(bytes);
  while (r.next() !== null) {
    /* consume every element to end of stream */
  }
  transcode(bytes); // second, independent full walk of the same bytes
}

test("malformed corpus is non-empty", () => assert.ok(malformed.length > 0));

for (const c of malformed) {
  test(`malformed [item ${c.item}] ${c.hex} — ${c.note}`, () => {
    assert.throws(
      () => walkAll(fromHex(c.hex)),
      // A clean decode error: a thrown Error, not a silent wrong value nor a
      // non-Error crash (TypeError from OOB indexing still counts as an Error,
      // but the fix should surface the port's own "truncated"/invalid message).
      (err: unknown) => err instanceof Error,
      `expected ${c.hex} to be cleanly rejected`,
    );
  });
}

test("malformed: all hostile inputs cleanly rejected", () => {
  let rejected = 0;
  for (const c of malformed) {
    let threw: unknown = null;
    try {
      walkAll(fromHex(c.hex));
    } catch (err) {
      threw = err;
    }
    assert.ok(threw !== null, `case ${c.hex} (${c.note}) decoded without throwing — WRONG VALUE`);
    assert.ok(threw instanceof Error, `case ${c.hex} threw a non-Error: ${String(threw)}`);
    rejected++;
  }
  console.log(`malformed: ${rejected}/${malformed.length} rejected`);
  assert.equal(rejected, malformed.length);
});
