"""Drives the Python implementation against the language-neutral contract in
conformance/vectors.json (generated by the Zig reference). Every vector must
reproduce in both directions."""

import json
import os
import unittest

from struple import from_json, to_json

_CORPUS = os.path.join(os.path.dirname(__file__), "..", "..", "conformance", "vectors.json")
with open(_CORPUS, encoding="utf-8") as _f:
    VECTORS = json.load(_f)


class Conformance(unittest.TestCase):
    def test_has_vectors(self):
        self.assertGreater(len(VECTORS), 0)

    def test_encode(self):
        for v in VECTORS:
            with self.subTest(json=v["json"]):
                self.assertEqual(from_json(v["json"]).hex(), v["bytes"])

    def test_decode(self):
        for v in VECTORS:
            with self.subTest(json=v["json"]):
                self.assertEqual(to_json(bytes.fromhex(v["bytes"])), v["json"])


if __name__ == "__main__":
    unittest.main()
