"""Drives the Python implementation against the language-neutral contract in
conformance/vectors.json (generated by the Zig reference). Every vector must
reproduce in both directions.

Two entry shapes:
  {json, bytes}  -- from_json(json) == bytes  and  to_json(bytes) == json
  {build, bytes} -- encode(build(op)) == bytes and transcode(bytes) == bytes
"""

import json
import os
import unittest

from struple import Writer, from_json, to_json, transcode

_CORPUS = os.path.join(os.path.dirname(__file__), "..", "..", "conformance", "vectors.json")
with open(_CORPUS, encoding="utf-8") as _f:
    VECTORS = json.load(_f)


def build_bytes(op):
    w = Writer()
    _build_into(w, op)
    return w.bytes()


def _build_into(w, op):
    (key, val), = op.items()
    if key == "nil":
        w.append_nil()
    elif key == "undef":
        w.append_undefined()
    elif key == "bool":
        w.append_bool(val)
    elif key == "int":
        w.append_int(int(val))
    elif key == "float64":
        w.append_float64(val)
    elif key == "float32":
        w.append_float32(val)
    elif key == "timestamp":
        w.append_timestamp(int(val))
    elif key == "string":
        w.append_string(val)
    elif key == "bytes":
        w.append_bytes(bytes.fromhex(val))
    elif key == "array":
        child = Writer()
        for o in val:
            _build_into(child, o)
        w.append_array(child.bytes())
    elif key == "set":
        w.append_set([_build_one(o) for o in val])
    elif key == "map":
        w.append_map([(_build_one(k), _build_one(v)) for k, v in val])
    else:
        raise ValueError(f"unknown op {key}")


def _build_one(op):
    w = Writer()
    _build_into(w, op)
    return w.bytes()


class Conformance(unittest.TestCase):
    def test_has_vectors(self):
        self.assertGreater(len(VECTORS), 0)

    def test_encode(self):
        for v in VECTORS:
            if "json" not in v:
                continue
            with self.subTest(json=v["json"]):
                self.assertEqual(from_json(v["json"]).hex(), v["bytes"])

    def test_decode(self):
        for v in VECTORS:
            if "json" not in v:
                continue
            with self.subTest(json=v["json"]):
                self.assertEqual(to_json(bytes.fromhex(v["bytes"])), v["json"])

    def test_build(self):
        for v in VECTORS:
            if "build" not in v:
                continue
            with self.subTest(build=v["build"]):
                self.assertEqual(build_bytes(v["build"]).hex(), v["bytes"])

    def test_transcode(self):
        for v in VECTORS:
            if "build" not in v:
                continue
            with self.subTest(build=v["build"]):
                self.assertEqual(transcode(bytes.fromhex(v["bytes"])).hex(), v["bytes"])


if __name__ == "__main__":
    unittest.main()
