"""Drives the Python implementation against the language-neutral contract in
conformance/vectors.json (generated by the Zig reference). Every vector must
reproduce in both directions.

Two entry shapes:
  {json, bytes}  -- from_json(json) == bytes  and  to_json(bytes) == json
  {build, bytes} -- encode(build(op)) == bytes and transcode(bytes) == bytes
"""

import json
import os
import unittest
from decimal import Decimal

from struple import Writer, encode, from_json, semantic_order, to_json, transcode, unpack

_CORPUS = os.path.join(os.path.dirname(__file__), "..", "..", "conformance", "vectors.json")
with open(_CORPUS, encoding="utf-8") as _f:
    VECTORS = json.load(_f)

_SEMANTIC = os.path.join(os.path.dirname(__file__), "..", "..", "conformance", "semantic_vectors.json")
with open(_SEMANTIC, encoding="utf-8") as _f:
    SEM_VECTORS = json.load(_f)


def build_bytes(op):
    w = Writer()
    _build_into(w, op)
    return w.bytes()


def _build_into(w, op):
    (key, val), = op.items()
    if key == "nil":
        w.append_nil()
    elif key == "undef":
        w.append_undefined()
    elif key == "bool":
        w.append_bool(val)
    elif key == "int":
        w.append_int(int(val))
    elif key == "float64":
        w.append_float64(val)
    elif key == "float32":
        w.append_float32(val)
    elif key == "decimal":
        w.append_decimal_string(val)
    elif key == "timestamp":
        w.append_timestamp(int(val))
    elif key == "uuid":
        w.append_uuid(bytes.fromhex(val))
    elif key == "string":
        w.append_string(val)
    elif key == "bytes":
        w.append_bytes(bytes.fromhex(val))
    elif key == "array":
        child = Writer()
        for o in val:
            _build_into(child, o)
        w.append_array(child.bytes())
    elif key == "set":
        w.append_set([_build_one(o) for o in val])
    elif key == "map":
        w.append_map([(_build_one(k), _build_one(v)) for k, v in val])
    else:
        raise ValueError(f"unknown op {key}")


def _build_one(op):
    w = Writer()
    _build_into(w, op)
    return w.bytes()


class Conformance(unittest.TestCase):
    def test_has_vectors(self):
        self.assertGreater(len(VECTORS), 0)

    def test_encode(self):
        for v in VECTORS:
            if "json" not in v:
                continue
            with self.subTest(json=v["json"]):
                self.assertEqual(from_json(v["json"]).hex(), v["bytes"])

    def test_decode(self):
        for v in VECTORS:
            if "json" not in v:
                continue
            with self.subTest(json=v["json"]):
                self.assertEqual(to_json(bytes.fromhex(v["bytes"])), v["json"])

    def test_build(self):
        for v in VECTORS:
            if "build" not in v:
                continue
            with self.subTest(build=v["build"]):
                self.assertEqual(build_bytes(v["build"]).hex(), v["bytes"])

    def test_transcode(self):
        for v in VECTORS:
            if "build" not in v:
                continue
            with self.subTest(build=v["build"]):
                self.assertEqual(transcode(bytes.fromhex(v["bytes"])).hex(), v["bytes"])

    def test_semantic_order(self):
        for sv in SEM_VECTORS:
            a, b = bytes.fromhex(sv["a"]), bytes.fromhex(sv["b"])
            with self.subTest(a=sv["a"], b=sv["b"]):
                self.assertEqual(semantic_order(a, b), sv["order"])


class DecimalUnit(unittest.TestCase):
    """Python-specific decimal behaviour beyond the shared corpus."""

    SANITY = {"12.345": "380321020d233300", "-12.345": "3801defdf2dcccff", "0": "3802"}

    def test_sanity_hex(self):
        for s, hexv in self.SANITY.items():
            self.assertEqual(Writer().append_decimal_string(s).bytes().hex(), hexv)

    def test_native_decimal_dispatch(self):
        # A native decimal.Decimal passed to the generic encode is detected.
        for s, hexv in self.SANITY.items():
            self.assertEqual(encode(Decimal(s)).hex(), hexv)

    def test_append_decimal_forms(self):
        # native Decimal, and the explicit (negative, digits, exp) triple
        self.assertEqual(Writer().append_decimal(Decimal("100")).bytes().hex(), "380321030b00")
        self.assertEqual(Writer().append_decimal(False, [1, 2, 3, 4, 5], -3).bytes().hex(), "380321020d233300")
        self.assertEqual(Writer().append_decimal(True, [1, 2, 3, 4, 5], -3).bytes().hex(), "3801defdf2dcccff")

    def test_round_trip(self):
        for s in ("12.345", "-12.345", "0", "100", "0.001", "12.300", "-0.5", "1e-9",
                  "123456789012345678901234567890.123456789"):
            enc = encode(Decimal(s))
            got = unpack(enc)[0]
            self.assertIsInstance(got, Decimal)
            self.assertEqual(got, Decimal(s))
            self.assertEqual(transcode(enc), enc)  # identity on canonical buffers

    def test_canonicalization(self):
        # 12.300 == 12.3 in value and in bytes (trailing zeros stripped)
        self.assertEqual(encode(Decimal("12.300")), encode(Decimal("12.3")))

    def test_json_render_one_way(self):
        cases = {"12.345": "12.345", "12.300": "12.3", "100": "100", "0.001": "0.001",
                 "-0.5": "-0.5", "0": "0", "1e-9": "0.000000001"}
        for s, want in cases.items():
            self.assertEqual(to_json(encode(Decimal(s))), want)

    def test_semantic_cross_type(self):
        # decimal joins the unified number class; exact via Fraction
        self.assertEqual(semantic_order(encode(Decimal("0.1")), encode(0.1)), -1)
        self.assertEqual(semantic_order(encode(Decimal("2.5")), encode(2.5)), 0)
        self.assertEqual(semantic_order(encode(Decimal("5")), encode(5)), 0)
        self.assertEqual(semantic_order(encode(Decimal("0")), encode(0)), 0)
        self.assertEqual(semantic_order(encode(Decimal("-0")), encode(-0.0)), 0)


if __name__ == "__main__":
    unittest.main()
