using System;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using Struple;

namespace Struple.Test;

/// <summary>
/// Drives the C# implementation against the language-neutral contract in
/// <c>conformance/vectors.json</c> (generated by the Zig reference) and
/// <c>conformance/semantic_vectors.json</c>, plus a behavioral suite (navigation / IndexedMap /
/// golden + round-trip). Prints a summary and exits nonzero on any failure.
///
/// <para>CWD must be <c>csharp/</c> so the corpus resolves at <c>../conformance/*.json</c>.</para>
/// </summary>
public static class Program
{
    private static int s_failures = 0;
    private static int s_checks = 0;

    public static int Main()
    {
        Conformance();
        Malformed();
        Behavioral();

        Console.WriteLine($"TOTAL: {s_checks} checks | {s_failures} failures");
        if (s_failures != 0)
        {
            Environment.Exit(1);
            return 1;
        }
        return 0;
    }

    // =======================================================================
    // Conformance corpus
    // =======================================================================

    private static void Conformance()
    {
        string corpus = File.ReadAllText("../conformance/vectors.json");
        var vectors = (List<object?>)Json.Parse(corpus)!;

        int jsonEnc = 0, jsonDec = 0, buildEnc = 0, buildTrc = 0;

        foreach (var o in vectors)
        {
            var v = (Json.JsonObject)o!;
            string want = (string)v.Get("bytes")!;
            byte[] bin = HexDecode(want);

            if (v.Has("json"))
            {
                string json = (string)v.Get("json")!;
                // encode: FromJson(json) == bytes
                string got = HexEncode(Json.FromJson(json));
                ExpectEq("json-encode [" + json + "]", got, want);
                jsonEnc++;
                // decode: ToJson(bytes) == json
                string back = Json.ToJson(bin);
                ExpectEq("json-decode [" + json + "]", back, json);
                jsonDec++;
            }
            else if (v.Has("build"))
            {
                object? op = v.Get("build");
                // encode: encode(build(op)) == bytes
                var w = new Struple.Packer();
                BuildInto(w, op);
                ExpectEq("build [" + want + "]", HexEncode(w.Bytes()), want);
                buildEnc++;
                // transcode: transcode(bytes) == bytes
                ExpectEq("transcode [" + want + "]", HexEncode(Transcode(bin)), want);
                buildTrc++;
                // one-way toJson pin (plain + scientific decimal rendering), when present
                if (v.Has("to_json"))
                {
                    string wantJson = (string)v.Get("to_json")!;
                    ExpectEq("to_json [" + want + "]", Json.ToJson(bin), wantJson);
                }
            }
        }

        // semantic-order corpus
        int semOk = 0;
        string semCorpus = File.ReadAllText("../conformance/semantic_vectors.json");
        var semVectors = (List<object?>)Json.Parse(semCorpus)!;
        foreach (var o in semVectors)
        {
            var pr = (Json.JsonObject)o!;
            byte[] a = HexDecode((string)pr.Get("a")!);
            byte[] b = HexDecode((string)pr.Get("b")!);
            int wantOrder = (int)(BigInteger)pr.Get("order")!;
            int got = Semantic.SemanticOrder(a, b);
            s_checks++;
            if (got != wantOrder)
            {
                Console.Error.WriteLine($"SEMANTIC FAIL {pr.Get("a")} <=> {pr.Get("b")}: got {got} want {wantOrder}");
                s_failures++;
            }
            else
            {
                semOk++;
            }
        }

        Console.WriteLine(
            $"Conformance: json encode {jsonEnc} decode {jsonDec} | build {buildEnc} transcode {buildTrc} | semantic {semOk} | {s_failures} failures");
    }

    // =======================================================================
    // Malformed / hostile corpus — every case MUST be rejected with the port's
    // own decode exception (StrupleException). A non-throw, or a native
    // exception of any other type (OverflowException, IndexOutOfRange, ...),
    // is a hardening FAILURE.
    // =======================================================================

    private static void Malformed()
    {
        string corpus = File.ReadAllText("../conformance/malformed.json");
        var doc = (Json.JsonObject)Json.Parse(corpus)!;
        var cases = (List<object?>)doc.Get("cases")!;

        int total = cases.Count;
        int rejected = 0;
        foreach (var o in cases)
        {
            var c = (Json.JsonObject)o!;
            string hex = (string)c.Get("hex")!;
            string note = (string)c.Get("note")!;
            byte[] bin = HexDecode(hex);

            s_checks++;
            bool ok = false;
            try
            {
                // Fully walk (decode + re-encode) the ENTIRE stream; a clean decoder
                // rejects the hostile bytes with StrupleException before completing.
                Transcode(bin);
                Console.Error.WriteLine($"MALFORMED FAIL [{hex}]: decoded without error (want StrupleException) — {note}");
            }
            catch (Struple.StrupleException)
            {
                ok = true;
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"MALFORMED FAIL [{hex}]: threw {ex.GetType().Name}, want StrupleException — {note}");
            }

            if (ok) rejected++;
            else s_failures++;
        }

        Console.WriteLine($"Malformed: {rejected}/{total} rejected | {s_failures} failures");
    }

    // -----------------------------------------------------------------------
    // Build-op interpreter — mirrors the Zig generator and the other ports.
    // -----------------------------------------------------------------------

    private static void BuildInto(Struple.Packer w, object? opObj)
    {
        var op = (Json.JsonObject)opObj!;
        string key = op.Keys[0];
        object? val = op.Values[0];
        switch (key)
        {
            case "nil": w.AppendNil(); break;
            case "undef": w.AppendUndefined(); break;
            case "bool": w.AppendBool((bool)val!); break;
            case "int": w.AppendBigInteger(BigInteger.Parse((string)val!)); break;
            case "float64": w.AppendFloat64(AsDouble(val)); break;
            case "float32": w.AppendFloat32((float)AsDouble(val)); break;
            case "timestamp": w.AppendTimestamp(long.Parse((string)val!)); break;
            case "uuid": w.AppendUuid(HexDecode((string)val!)); break;
            case "decimal": w.AppendDecimalString((string)val!); break;
            case "string": w.AppendString((string)val!); break;
            case "bytes": w.AppendBytes(HexDecode((string)val!)); break;
            case "array":
            {
                var child = new Struple.Packer();
                foreach (var item in AsList(val)) BuildInto(child, item);
                w.AppendArray(child.Bytes());
                break;
            }
            case "set":
            {
                var elems = new List<byte[]>();
                foreach (var item in AsList(val)) elems.Add(BuildOne(item));
                w.AppendSet(elems);
                break;
            }
            case "map":
            {
                var entries = new List<byte[][]>();
                foreach (var pairObj in AsList(val))
                {
                    var pair = AsList(pairObj);
                    entries.Add(new[] { BuildOne(pair[0]), BuildOne(pair[1]) });
                }
                w.AppendMap(entries);
                break;
            }
            default:
                throw new Exception("unknown op " + key);
        }
    }

    private static byte[] BuildOne(object? op)
    {
        var w = new Struple.Packer();
        BuildInto(w, op);
        return w.Bytes();
    }

    private static List<object?> AsList(object? o) => (List<object?>)o!;

    private static double AsDouble(object? val)
    {
        if (val is double d) return d;
        if (val is BigInteger i) return (double)i;
        return 0.0;
    }

    // -----------------------------------------------------------------------
    // transcode: decode every element and re-encode it (decoder round-trip).
    // -----------------------------------------------------------------------

    private static byte[] Transcode(byte[] data)
    {
        var r = new Struple.Reader(data);
        var outP = new Struple.Packer();
        Struple.Element? e;
        while ((e = r.Next()) != null)
        {
            AppendElement(outP, e);
        }
        return outP.Bytes();
    }

    private static void AppendElement(Struple.Packer outP, Struple.Element e)
    {
        switch (e.Kind)
        {
            case Struple.Kind.Nil: outP.AppendNil(); break;
            case Struple.Kind.Undef: outP.AppendUndefined(); break;
            case Struple.Kind.Boolean: outP.AppendBool(e.BoolValue); break;
            case Struple.Kind.Int:
            case Struple.Kind.BigIntKind:
                outP.AppendBigInteger(e.IntValue);
                break;
            case Struple.Kind.Float32: outP.AppendFloat32(e.Float32Value); break;
            case Struple.Kind.Float64: outP.AppendFloat64(e.Float64Value); break;
            case Struple.Kind.Decimal:
            {
                var d = e.Decimal!;
                outP.AppendDecimal(d.Negative, d.CoefficientDigits(), (int)d.Exponent());
                break;
            }
            case Struple.Kind.Timestamp: outP.AppendTimestamp(e.TimestampValue); break;
            case Struple.Kind.Uuid: outP.AppendUuid(e.UuidValue); break;
            case Struple.Kind.String: outP.AppendStringBytes(e.StringBytes); break;
            case Struple.Kind.Bytes: outP.AppendBytes(e.BytesValue); break;
            case Struple.Kind.Array: outP.AppendContainerBody(Struple.Array, e.Inner); break;
            case Struple.Kind.Map: outP.AppendContainerBody(Struple.Map, e.Inner); break;
            case Struple.Kind.Set: outP.AppendContainerBody(Struple.Set, e.Inner); break;
            default: throw new InvalidOperationException();
        }
    }

    // =======================================================================
    // Behavioral suite (navigation / IndexedMap / golden + round-trip),
    // mirroring src/tests.zig and the sibling ports' TestStruple.
    // =======================================================================

    private static void Behavioral()
    {
        GoldenScalars();
        GoldenDecimals();
        RoundTripDecimals();
        GoldenUuid();
        RoundTripIntegers();
        NavStreamOps();
        NavPredicatesAndDescent();
        NavMapLookup();
        NavIndexedMap();
        SemanticSpot();
        DepthCap();

        Console.WriteLine($"Behavioral: complete ({s_failures} failures so far)");
    }

    private static byte[] EncStr(string s) => new Struple.Packer().AppendString(s).Bytes();
    private static byte[] EncInt(long v) => new Struple.Packer().AppendInt(v).Bytes();

    private static BigInteger IntOf(byte[]? view) => new Struple.Reader(view!).Next()!.IntValue;
    private static string StrOf(byte[]? view) => new Struple.Reader(view!).Next()!.StringValue;

    private static void GoldenScalars()
    {
        CheckHex("nil", new Struple.Packer().AppendNil().Bytes(), "01");
        CheckHex("undef", new Struple.Packer().AppendUndefined().Bytes(), "02");
        CheckHex("false", new Struple.Packer().AppendBool(false).Bytes(), "05");
        CheckHex("true", new Struple.Packer().AppendBool(true).Bytes(), "06");
        CheckHex("int 0", EncInt(0), "20");
        CheckHex("int 12345", EncInt(12345), "223039");
        CheckHex("int -1", EncInt(-1), "1fff");
        CheckHex("int 256", EncInt(256), "220100");
        CheckHex("string app", EncStr("app"), "4861707000");
        CheckHex("float64 1.5", new Struple.Packer().AppendFloat64(1.5).Bytes(), "35bff8000000000000");
        CheckHex("float32 1.5", new Struple.Packer().AppendFloat32(1.5f).Bytes(), "34bfc00000");
        CheckHex("timestamp 0", new Struple.Packer().AppendTimestamp(0).Bytes(), "408000000000000000");
    }

    private static void GoldenDecimals()
    {
        CheckHex("dec 0", new Struple.Packer().AppendDecimalString("0").Bytes(), "3802");
        CheckHex("dec 12.345", new Struple.Packer().AppendDecimalString("12.345").Bytes(), "380321020d233300");
        CheckHex("dec -12.345", new Struple.Packer().AppendDecimalString("-12.345").Bytes(), "3801defdf2dcccff");
        CheckHex("dec 100", new Struple.Packer().AppendDecimalString("100").Bytes(), "380321030b00");
        CheckHex("dec 0.001", new Struple.Packer().AppendDecimalString("0.001").Bytes(), "38031ffe0b00");
        // canonicalization: 12.300 == 12.3
        CheckHex("dec 12.300", new Struple.Packer().AppendDecimalString("12.300").Bytes(), "380321020d1f00");
        // native System.Decimal dispatch agrees with the string form
        CheckHex("dec System.Decimal 12.345", new Struple.Packer().AppendDecimal(12.345m).Bytes(), "380321020d233300");
        // explicit (negative, digits, exp) triple
        CheckHex("dec triple 12.345", new Struple.Packer().AppendDecimal(false, new[] { 1, 2, 3, 4, 5 }, -3).Bytes(), "380321020d233300");
        Check(Struple.BytesEqual(new Struple.Packer().AppendDecimal(12.300m).Bytes(),
                new Struple.Packer().AppendDecimal(12.3m).Bytes()),
            "dec 12.300 == 12.3 bytes");
    }

    private static void RoundTripDecimals()
    {
        string[] samples = { "0", "5", "-5", "12.345", "-12.345", "0.001", "100", "9.99", "1e30",
            "1e-9", "-0.5", "123456789012345678901234567890.123456789" };
        foreach (string s in samples)
        {
            byte[] enc = new Struple.Packer().AppendDecimalString(s).Bytes();
            var e = new Struple.Reader(enc).Next()!;
            Check(e.Kind == Struple.Kind.Decimal, "decimal kind " + s);
            var d = e.Decimal!;
            byte[] re = new Struple.Packer().AppendDecimal(d.Negative, d.CoefficientDigits(), (int)d.Exponent()).Bytes();
            Check(Struple.BytesEqual(enc, re), "decimal repack " + s);
        }
        // fully-specified decode: 12.345 = +12345 x 10^-3
        var de = new Struple.Reader(new Struple.Packer().AppendDecimalString("12.345").Bytes()).Next()!.Decimal!;
        Check(!de.Negative && !de.IsZero, "12.345 sign");
        Check(de.DigitCount() == 5, "12.345 digitCount");
        Check(de.Exponent() == -3, "12.345 exponent");
        Check(IntArrayEqual(de.CoefficientDigits(), new[] { 1, 2, 3, 4, 5 }), "12.345 digits");
    }

    private static void GoldenUuid()
    {
        byte[] u = { 0x55, 0x0e, 0x84, 0x00, 0xe2, 0x9b, 0x41, 0xd4, 0xa7, 0x16, 0x44, 0x66, 0x55, 0x44, 0x00, 0x00 };
        byte[] enc = new Struple.Packer().AppendUuid(u).Bytes();
        CheckHex("uuid golden", enc, "44550e8400e29b41d4a716446655440000");
        var e = new Struple.Reader(enc).Next()!;
        Check(e.Kind == Struple.Kind.Uuid && Struple.BytesEqual(e.UuidValue, u), "uuid round-trip");
        // System.Guid overload agrees
        var ju = Guid.Parse("550e8400-e29b-41d4-a716-446655440000");
        CheckHex("uuid from Guid", new Struple.Packer().AppendUuid(ju).Bytes(), "44550e8400e29b41d4a716446655440000");
    }

    private static void RoundTripIntegers()
    {
        long[] cases = { long.MinValue, -1_000_000_000_000L, -65537, -65536, -257, -256, -255, -100,
            -2, -1, 0, 1, 2, 100, 255, 256, 257, 65535, 65536, 1_000_000_000_000L, long.MaxValue };
        foreach (long v in cases)
        {
            byte[] buf = EncInt(v);
            var e = new Struple.Reader(buf).Next()!;
            Check(e.IntValue == new BigInteger(v), "int round-trip " + v);
        }
        BigInteger[] wide = {
            BigInteger.One << 64, -(BigInteger.One << 64),
            BigInteger.One << 100, -(BigInteger.One << 100),
            Struple.I128Max, Struple.I128Min,
            BigInteger.One << 127,                  // first big-int positive
            Struple.I128Min - BigInteger.One,        // first big-int negative
            BigInteger.Parse("100000000000000000000000000000"),
            BigInteger.Parse("-99999999999999999999999999999999") };
        foreach (BigInteger v in wide)
        {
            byte[] buf = new Struple.Packer().AppendBigInteger(v).Bytes();
            var e = new Struple.Reader(buf).Next()!;
            Check(e.IntValue == v, "bigint round-trip " + v);
        }
    }

    private static void NavStreamOps()
    {
        var child = new Struple.Packer().AppendInt(1).AppendInt(2).AppendInt(3);
        byte[] buf = new Struple.Packer().AppendString("users").AppendInt(12345).AppendBool(true)
            .AppendArray(child.Bytes()).Bytes();
        var v = Navigate.NewView(buf);
        Check(v.Count() == 4, "count == 4");
        Check(v.HeadType() == Struple.String, "headType string");
        Check(StrOf(v.At(0)) == "users", "at(0) users");
        Check(IntOf(v.At(1)) == new BigInteger(12345), "at(1) 12345");
        Check(v.At(4) == null, "at(4) null");
        Check(Struple.BytesEqual(v.Head()!, v.At(0)!), "head == at(0)");
        Check(new Navigate.View(v.Tail()).Count() == 3, "tail count 3");
        Check(new Navigate.View(v.NthRest(2)).Count() == 2, "nthRest(2) count 2");
        byte[] tk = v.Take(2);
        Check(new Navigate.View(tk).Count() == 2, "take(2) count 2");
        var prefix = new byte[tk.Length];
        System.Array.Copy(buf, prefix, tk.Length);
        Check(Struple.BytesEqual(tk, prefix), "take prefix");
    }

    private static void NavPredicatesAndDescent()
    {
        Check(Navigate.NewView(EncStr("x")).IsString(), "isString");
        var i5 = Navigate.NewView(EncInt(5));
        Check(i5.IsInt() && i5.IsNumber() && !i5.IsFloat(), "isInt/isNumber");
        var f = Navigate.NewView(new Struple.Packer().AppendFloat64(1.5).Bytes());
        Check(f.IsFloat() && f.IsNumber() && !f.IsInt(), "isFloat");
        Check(Navigate.NewView(new Struple.Packer().AppendNil().Bytes()).IsNil(), "isNil");
        Check(Navigate.NewView(new Struple.Packer().AppendBool(true).Bytes()).IsBool(), "isBool");
        Check(Navigate.NewView(new Struple.Packer().AppendDecimalString("1.5").Bytes()).IsDecimal(), "isDecimal");

        var child = new Struple.Packer().AppendInt(10).AppendInt(20);
        var v = Navigate.NewView(new Struple.Packer().AppendArray(child.Bytes()).Bytes());
        Check(v.IsArray() && v.IsContainer(), "isArray/isContainer");
        Check(v.Count() == 1, "array top count 1");
        var inner = new Navigate.View(v.ContainedItems()!);
        Check(inner.Count() == 2, "inner count 2");
        Check(IntOf(inner.At(0)) == new BigInteger(10), "inner at(0) 10");
        Check(IntOf(inner.At(1)) == new BigInteger(20), "inner at(1) 20");
    }

    private static void NavMapLookup()
    {
        // {"c":3,"a":1,"b":2} out of order -> canonical
        var entries = new List<byte[][]>
        {
            new[] { EncStr("c"), EncInt(3) },
            new[] { EncStr("a"), EncInt(1) },
            new[] { EncStr("b"), EncInt(2) },
        };
        byte[] buf = new Struple.Packer().AppendMap(entries).Bytes();
        var v = Navigate.NewView(buf);
        Check(v.IsMap(), "isMap");
        var m = new Navigate.MapView(v.ContainedItems()!);
        Check(m.Count() == 3, "map count 3");
        Check(IntOf(m.Get(EncStr("b"))) == new BigInteger(2), "map get b == 2");
        Check(m.Get(EncStr("z")) == null, "map get z == null (past end)");
        Check(m.Get(EncStr("aa")) == null, "map get aa == null (middle)");
        var keys = new List<string>();
        foreach (var e in m.Entries()) keys.Add(StrOf(e.Key));
        Check(ListEqual(keys, new List<string> { "a", "b", "c" }), "map keys sorted");
    }

    private static void NavIndexedMap()
    {
        string[] keys = { "h", "c", "a", "g", "d", "f", "b", "e" };
        var entries = new List<byte[][]>();
        for (int i = 0; i < keys.Length; i++)
        {
            entries.Add(new[] { EncStr(keys[i]), EncInt(i + 1) });
        }
        byte[] inner = Navigate.NewView(new Struple.Packer().AppendMap(entries).Bytes()).ContainedItems()!;
        var im = new Navigate.IndexedMap(inner);

        Check(im.Count() == 8, "indexed count 8");

        string abc = "abcdefgh";
        for (int i = 0; i < 8; i++)
        {
            Check(StrOf(im.At(i)!.Key) == abc[i].ToString(), "indexed at(" + i + ")");
        }
        Check(im.At(8) == null, "indexed at(8) null");

        var m = new Navigate.MapView(inner);
        foreach (char ch in abc)
        {
            byte[] key = EncStr(ch.ToString());
            Check(Struple.BytesEqual(im.Get(key)!, m.Get(key)!), "indexed get matches linear " + ch);
        }

        Check(im.Find(EncStr("e")) == 4, "find e == 4");
        Check(IntOf(im.Get(EncStr("e"))) == new BigInteger(8), "get e == 8");

        Check(im.Get(EncStr("A")) == null, "get A == null (below)");
        Check(im.Get(EncStr("cc")) == null, "get cc == null (between)");
        Check(im.Get(EncStr("z")) == null, "get z == null (above)");
        Check(im.Find(EncStr("cc")) == null, "find cc == null");
        Check(im.Find(EncStr("a")) == 0, "find a == 0");
        Check(im.Find(EncStr("h")) == 7, "find h == 7");

        var listed = new List<string>();
        foreach (var e in im) listed.Add(StrOf(e.Key));
        Check(ListEqual(listed, new List<string> { "a", "b", "c", "d", "e", "f", "g", "h" }), "indexed iteration");

        var im2 = new Navigate.MapView(inner).Indexed();
        Check(im2.Count() == 8, "indexed() shortcut count");
        Check(Struple.BytesEqual(im2.Get(EncStr("e"))!, im.Get(EncStr("e"))!), "indexed() get e");
    }

    private static void SemanticSpot()
    {
        Check(Semantic.SemanticOrder(EncInt(5), new Struple.Packer().AppendFloat64(5.0).Bytes()) == 0,
            "sem int 5 == float 5.0");
        Check(Semantic.SemanticOrder(new Struple.Packer().AppendDecimalString("0.1").Bytes(),
            new Struple.Packer().AppendFloat64(0.1).Bytes()) == -1, "sem decimal 0.1 < float 0.1");
        Check(Semantic.SemanticOrder(new Struple.Packer().AppendDecimalString("2.5").Bytes(),
            new Struple.Packer().AppendFloat64(2.5).Bytes()) == 0, "sem decimal 2.5 == float 2.5");
        Check(Semantic.SemanticOrder(new Struple.Packer().AppendNil().Bytes(),
            new Struple.Packer().AppendBool(false).Bytes()) == -1, "sem nil < bool");
    }

    // Recursion depth caps (HARDENING Item 5): hostile deeply-nested input must be rejected with
    // the port's own StrupleException, never an uncatchable StackOverflowException. Mirrors the
    // Zig "depth cap" test.
    private static void DepthCap()
    {
        // fromJson: a 1000-deep bracket string (> MaxDepth) rejects on the recursive-descent cap.
        string deepJson = new string('[', 1000) + new string(']', 1000);
        CheckThrows(() => Json.FromJson(deepJson), "depth cap: 1000-deep JSON rejected");

        // Build a ~300-deep nested array via the port's OWN encoder (wrap the prior bytes 300x),
        // then ToJson / SemanticOrder must reject it at the cap rather than recursing to overflow.
        byte[] deep = new Struple.Packer().AppendInt(0).Bytes();
        for (int d = 0; d < 300; d++)
        {
            deep = new Struple.Packer().AppendArray(deep).Bytes();
        }
        CheckThrows(() => Json.ToJson(deep), "depth cap: 300-deep ToJson rejected");
        CheckThrows(() => Semantic.SemanticOrder(deep, deep), "depth cap: 300-deep SemanticOrder rejected");
    }

    // =======================================================================
    // helpers
    // =======================================================================

    /// <summary>Assert <paramref name="action"/> throws a <see cref="Struple.StrupleException"/> (any
    /// other exception type — e.g. StackOverflow surrogate — is a hardening FAILURE).</summary>
    private static void CheckThrows(Action action, string label)
    {
        s_checks++;
        try
        {
            action();
            Console.Error.WriteLine("FAIL " + label + ": no exception (want StrupleException)");
            s_failures++;
        }
        catch (Struple.StrupleException)
        {
            // expected
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("FAIL " + label + ": threw " + ex.GetType().Name + ", want StrupleException");
            s_failures++;
        }
    }

    private static void Check(bool cond, string label)
    {
        s_checks++;
        if (!cond)
        {
            Console.Error.WriteLine("FAIL " + label);
            s_failures++;
        }
    }

    private static void CheckHex(string label, byte[] got, string want)
    {
        Check(HexEncode(got) == want, label + " (got " + HexEncode(got) + " want " + want + ")");
    }

    private static void ExpectEq(string label, string got, string want)
    {
        s_checks++;
        if (got != want)
        {
            Console.Error.WriteLine("FAIL " + label + ": got " + got + " want " + want);
            s_failures++;
        }
    }

    private static byte[] HexDecode(string hex)
    {
        int n = hex.Length / 2;
        var b = new byte[n];
        for (int i = 0; i < n; i++)
        {
            b[i] = Convert.ToByte(hex.Substring(i * 2, 2), 16);
        }
        return b;
    }

    private static string HexEncode(byte[] data)
    {
        var sb = new System.Text.StringBuilder(data.Length * 2);
        foreach (byte x in data)
        {
            sb.Append("0123456789abcdef"[(x >> 4) & 0xF]);
            sb.Append("0123456789abcdef"[x & 0xF]);
        }
        return sb.ToString();
    }

    private static bool IntArrayEqual(int[] a, int[] b)
    {
        if (a.Length != b.Length) return false;
        for (int i = 0; i < a.Length; i++) if (a[i] != b[i]) return false;
        return true;
    }

    private static bool ListEqual(List<string> a, List<string> b)
    {
        if (a.Count != b.Count) return false;
        for (int i = 0; i < a.Count; i++) if (a[i] != b[i]) return false;
        return true;
    }
}
