package struple

// Drives the Go implementation against the language-neutral contract in
// conformance/vectors.json and conformance/semantic_vectors.json (generated by
// the Zig reference). Every vector must reproduce in both directions.

import (
	"encoding/hex"
	"fmt"
	"os"
	"strconv"
	"testing"
	"time"
)

func loadCorpus(t *testing.T, name string) []jsonValue {
	t.Helper()
	text, err := os.ReadFile("../conformance/" + name)
	if err != nil {
		t.Fatalf("read %s: %v", name, err)
	}
	v, err := parseJSON(string(text))
	if err != nil {
		t.Fatalf("parse %s: %v", name, err)
	}
	if v.kind != jArray {
		t.Fatalf("%s is not an array", name)
	}
	return v.arr
}

func field(obj jsonValue, key string) (jsonValue, bool) {
	if obj.kind != jObject {
		return jsonValue{}, false
	}
	for _, m := range obj.obj {
		if m.key == key {
			return m.val, true
		}
	}
	return jsonValue{}, false
}

func asStr(t *testing.T, j jsonValue) string {
	t.Helper()
	if j.kind != jStr {
		t.Fatalf("expected string, got kind %d", j.kind)
	}
	return j.str
}

func toHex(b []byte) string { return hex.EncodeToString(b) }

func fromHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex %q: %v", s, err)
	}
	return b
}

// buildInto interprets a build op into encoded bytes — mirrors the Zig generator
// and the other languages' conformance tests.
func buildInto(t *testing.T, w *Writer, op jsonValue) {
	t.Helper()
	if op.kind != jObject || len(op.obj) == 0 {
		t.Fatalf("op must be a one-key object")
	}
	key := op.obj[0].key
	val := op.obj[0].val
	switch key {
	case "nil":
		w.AppendNil()
	case "undef":
		w.AppendUndefined()
	case "bool":
		w.AppendBool(val.kind == jBool && val.boolVal)
	case "int":
		n, err := strconv.ParseInt(asStr(t, val), 10, 64)
		if err != nil {
			t.Fatalf("bad int %q: %v", val.str, err)
		}
		w.AppendInt(n)
	case "float64":
		w.AppendF64(opFloat(t, val))
	case "float32":
		w.AppendF32(float32(opFloat(t, val)))
	case "decimal":
		if err := w.AppendDecimalString(asStr(t, val)); err != nil {
			t.Fatalf("bad decimal %q: %v", val.str, err)
		}
	case "timestamp":
		n, err := strconv.ParseInt(asStr(t, val), 10, 64)
		if err != nil {
			t.Fatalf("bad timestamp %q: %v", val.str, err)
		}
		w.AppendTimestamp(n)
	case "uuid":
		raw := fromHex(t, asStr(t, val))
		if len(raw) != 16 {
			t.Fatalf("uuid must be 16 bytes, got %d", len(raw))
		}
		var u [16]byte
		copy(u[:], raw)
		w.AppendUUID(u)
	case "string":
		w.AppendString(asStr(t, val))
	case "bytes":
		w.AppendBytes(fromHex(t, asStr(t, val)))
	case "array":
		child := NewWriter()
		for _, item := range val.arr {
			buildInto(t, child, item)
		}
		w.AppendArray(child.Bytes())
	case "set":
		elems := make([][]byte, 0, len(val.arr))
		for _, item := range val.arr {
			ep := NewWriter()
			buildInto(t, ep, item)
			// copy: each sub-writer reuses its own buffer, but AppendSet keeps
			// references until it sorts/dedups — distinct writers so safe.
			elems = append(elems, ep.Bytes())
		}
		w.AppendSet(elems)
	case "map":
		entries := make([][2][]byte, 0, len(val.arr))
		for _, pair := range val.arr {
			kp := NewWriter()
			buildInto(t, kp, pair.arr[0])
			vp := NewWriter()
			buildInto(t, vp, pair.arr[1])
			entries = append(entries, [2][]byte{kp.Bytes(), vp.Bytes()})
		}
		w.AppendMap(entries)
	default:
		t.Fatalf("unknown op %q", key)
	}
}

func opFloat(t *testing.T, j jsonValue) float64 {
	t.Helper()
	switch j.kind {
	case jFloat:
		return j.floatV
	case jInt:
		return float64(j.intVal)
	default:
		t.Fatalf("expected number op value, got kind %d", j.kind)
		return 0
	}
}

func buildOne(t *testing.T, op jsonValue) []byte {
	w := NewWriter()
	buildInto(t, w, op)
	return w.Bytes()
}

func TestCorpusHasVectors(t *testing.T) {
	if len(loadCorpus(t, "vectors.json")) == 0 {
		t.Fatal("empty corpus")
	}
}

func TestJSONEncode(t *testing.T) {
	for _, v := range loadCorpus(t, "vectors.json") {
		j, ok := field(v, "json")
		if !ok {
			continue
		}
		want, _ := field(v, "bytes")
		got, err := FromJson(asStr(t, j))
		if err != nil {
			t.Fatalf("FromJson(%s): %v", asStr(t, j), err)
		}
		if toHex(got) != asStr(t, want) {
			t.Errorf("encode %s\n got %s\nwant %s", asStr(t, j), toHex(got), asStr(t, want))
		}
	}
}

func TestJSONDecode(t *testing.T) {
	for _, v := range loadCorpus(t, "vectors.json") {
		j, ok := field(v, "json")
		if !ok {
			continue
		}
		bytesField, _ := field(v, "bytes")
		got, err := ToJson(fromHex(t, asStr(t, bytesField)))
		if err != nil {
			t.Fatalf("ToJson(%s): %v", asStr(t, bytesField), err)
		}
		if got != asStr(t, j) {
			t.Errorf("decode %s\n got %s\nwant %s", asStr(t, bytesField), got, asStr(t, j))
		}
	}
}

func TestBuildEncode(t *testing.T) {
	for _, v := range loadCorpus(t, "vectors.json") {
		op, ok := field(v, "build")
		if !ok {
			continue
		}
		want, _ := field(v, "bytes")
		got := buildOne(t, op)
		if toHex(got) != asStr(t, want) {
			t.Errorf("build %v\n got %s\nwant %s", op, toHex(got), asStr(t, want))
		}
	}
}

func TestBuildTranscode(t *testing.T) {
	for _, v := range loadCorpus(t, "vectors.json") {
		if _, ok := field(v, "build"); !ok {
			continue
		}
		bytesField, _ := field(v, "bytes")
		in := fromHex(t, asStr(t, bytesField))
		got, err := Transcode(in)
		if err != nil {
			t.Fatalf("Transcode(%s): %v", asStr(t, bytesField), err)
		}
		if toHex(got) != asStr(t, bytesField) {
			t.Errorf("transcode %s\n got %s", asStr(t, bytesField), toHex(got))
		}
	}
}

// TestBuildToJson pins the plain + scientific decimal rendering: for every build
// vector that carries a one-way "to_json" field, ToJson(bytes) must equal it
// byte-for-byte. Vectors without the field are unaffected (Item 2, part 5).
func TestBuildToJson(t *testing.T) {
	for _, v := range loadCorpus(t, "vectors.json") {
		if _, ok := field(v, "build"); !ok {
			continue
		}
		tj, ok := field(v, "to_json")
		if !ok {
			continue
		}
		bytesField, _ := field(v, "bytes")
		got, err := ToJson(fromHex(t, asStr(t, bytesField)))
		if err != nil {
			t.Fatalf("ToJson(%s): %v", asStr(t, bytesField), err)
		}
		if got != asStr(t, tj) {
			t.Errorf("to_json %s\n got %s\nwant %s", asStr(t, bytesField), got, asStr(t, tj))
		}
	}
}

// loadMalformed reads conformance/malformed.json — the negative counterpart to
// vectors.json. Its top level is an object { "description", "cases": [...] }, so
// (unlike loadCorpus) it pulls out the "cases" array.
func loadMalformed(t *testing.T) []jsonValue {
	t.Helper()
	text, err := os.ReadFile("../conformance/malformed.json")
	if err != nil {
		t.Fatalf("read malformed.json: %v", err)
	}
	v, err := parseJSON(string(text))
	if err != nil {
		t.Fatalf("parse malformed.json: %v", err)
	}
	cases, ok := field(v, "cases")
	if !ok || cases.kind != jArray {
		t.Fatalf("malformed.json: missing \"cases\" array")
	}
	return cases.arr
}

// decodeWalk decodes every element of buf in sequence, returning the first decode
// error (nil means the whole buffer decoded as a valid stream — which for a
// malformed case is itself a failure). Any panic is captured and surfaced via
// panicked=true; the hardening fix must make a decode-time panic impossible, so
// the test treats a panic as a hard failure rather than a clean rejection.
func decodeWalk(buf []byte) (err error, panicked bool) {
	defer func() {
		if r := recover(); r != nil {
			panicked = true
			err = fmt.Errorf("panic: %v", r)
		}
	}()
	r := NewReader(buf)
	for {
		_, ok, e := r.Next()
		if e != nil {
			return e, false
		}
		if !ok {
			return nil, false
		}
	}
}

// transcodeSafe runs Transcode (which walks and re-encodes the entire stream)
// under a recover guard, so a stray panic is reported rather than crashing the
// test binary.
func transcodeSafe(buf []byte) (err error, panicked bool) {
	defer func() {
		if r := recover(); r != nil {
			panicked = true
			err = fmt.Errorf("panic: %v", r)
		}
	}()
	_, err = Transcode(buf)
	return err, false
}

// TestMalformedRejected asserts every hostile encoding in malformed.json is
// rejected cleanly by a full-stream walk (Reader.Next loop) and by Transcode —
// a non-nil decode error, never a panic, crash, or silently-accepted value.
func TestMalformedRejected(t *testing.T) {
	cases := loadMalformed(t)
	if len(cases) == 0 {
		t.Fatal("malformed corpus is empty")
	}
	rejected := 0
	for _, c := range cases {
		hexField, _ := field(c, "hex")
		hexStr := asStr(t, hexField)
		note := ""
		if nf, ok := field(c, "note"); ok && nf.kind == jStr {
			note = nf.str
		}
		buf := fromHex(t, hexStr)

		// Path 1: raw element walk.
		err, panicked := decodeWalk(buf)
		if panicked {
			t.Errorf("malformed %s: PANICKED during walk (must reject cleanly) — %s", hexStr, note)
			continue
		}
		if err == nil {
			t.Errorf("malformed %s: accepted as valid by walk (want a decode error) — %s", hexStr, note)
			continue
		}
		// Path 2: Transcode the whole stream.
		tErr, tPanicked := transcodeSafe(buf)
		if tPanicked {
			t.Errorf("malformed %s: Transcode PANICKED (must reject cleanly) — %s", hexStr, note)
			continue
		}
		if tErr == nil {
			t.Errorf("malformed %s: Transcode accepted as valid (want a decode error) — %s", hexStr, note)
			continue
		}
		rejected++
	}
	t.Logf("malformed: %d/%d rejected", rejected, len(cases))
	if rejected != len(cases) {
		t.Fatalf("malformed corpus: only %d of %d cases rejected cleanly", rejected, len(cases))
	}
}

// TestDecimalItem2 covers the encode-side exponent bounds and the semantic DoS
// short-circuit for decimals (Item 2). The decode-side i32 cap is exercised by
// the malformed corpus (380324800000000b00) and the scientific/plain toJson
// rendering by TestBuildToJson.
func TestDecimalItem2(t *testing.T) {
	// Encode bounds: an exponent literal or adjusted exponent past i32 rejects;
	// adjusted exponent == i32 max is accepted.
	encCases := []struct {
		s    string
		want bool // true => must reject
	}{
		{"1e9999999999", true},  // exponent literal far beyond i32
		{"1e2147483647", true},  // adjusted exponent 2^31 (out of range)
		{"1e2147483646", false}, // adjusted exponent == i32 max (valid)
	}
	for _, c := range encCases {
		w := NewWriter()
		err := w.AppendDecimalString(c.s)
		if c.want && err != ErrInvalidDecimal {
			t.Errorf("AppendDecimalString(%q) = %v, want ErrInvalidDecimal", c.s, err)
		}
		if !c.want && err != nil {
			t.Errorf("AppendDecimalString(%q) = %v, want nil", c.s, err)
		}
	}

	// Semantic short-circuit: an astronomically large/small (but i32-valid)
	// exponent must decide by order of magnitude and return PROMPTLY — never
	// materialize a 2^31-scaled value. A hang (no return) is a hard failure.
	build := func(s string) []byte {
		w := NewWriter()
		if err := w.AppendDecimalString(s); err != nil {
			t.Fatalf("build %q: %v", s, err)
		}
		return append([]byte(nil), w.Bytes()...)
	}
	buildInt := func(v int64) []byte {
		w := NewWriter()
		w.AppendInt(v)
		return append([]byte(nil), w.Bytes()...)
	}
	buildF64 := func(v float64) []byte {
		w := NewWriter()
		w.AppendF64(v)
		return append([]byte(nil), w.Bytes()...)
	}
	huge := build("1e2000000000")
	tiny := build("1e-2000000000")
	five := buildInt(5)
	onef := buildF64(1.0)

	semCases := []struct {
		name string
		a, b []byte
		want int
	}{
		{"1e2000000000 > int 5", huge, five, 1},
		{"1e-2000000000 < int 5", tiny, five, -1},
		{"1e2000000000 > 1.0", huge, onef, 1},
		{"1e-2000000000 < 1.0", tiny, onef, -1},
	}
	for _, c := range semCases {
		done := make(chan struct{})
		var got int
		var err error
		go func() {
			got, err = SemanticOrder(c.a, c.b)
			close(done)
		}()
		select {
		case <-done:
			if err != nil {
				t.Errorf("%s: SemanticOrder error: %v", c.name, err)
			} else if got != c.want {
				t.Errorf("%s: got %d, want %d", c.name, got, c.want)
			}
		case <-time.After(3 * time.Second):
			t.Fatalf("%s: SemanticOrder did not return within 3s — the DoS short-circuit is wrong", c.name)
		}
	}
}

func TestSemanticCorpus(t *testing.T) {
	for _, pr := range loadCorpus(t, "semantic_vectors.json") {
		aField, _ := field(pr, "a")
		bField, _ := field(pr, "b")
		orderField, _ := field(pr, "order")
		if orderField.kind != jInt {
			t.Fatalf("order is not an integer")
		}
		want := orderField.intVal
		got, err := SemanticOrder(fromHex(t, asStr(t, aField)), fromHex(t, asStr(t, bField)))
		if err != nil {
			t.Fatalf("SemanticOrder(%s, %s): %v", asStr(t, aField), asStr(t, bField), err)
		}
		if int64(got) != want {
			t.Errorf("semantic %s <=> %s: got %d want %d", asStr(t, aField), asStr(t, bField), got, want)
		}
	}
}
