package struple

// Drives the Go implementation against the language-neutral contract in
// conformance/vectors.json and conformance/semantic_vectors.json (generated by
// the Zig reference). Every vector must reproduce in both directions.

import (
	"encoding/hex"
	"os"
	"strconv"
	"testing"
)

func loadCorpus(t *testing.T, name string) []jsonValue {
	t.Helper()
	text, err := os.ReadFile("../conformance/" + name)
	if err != nil {
		t.Fatalf("read %s: %v", name, err)
	}
	v, err := parseJSON(string(text))
	if err != nil {
		t.Fatalf("parse %s: %v", name, err)
	}
	if v.kind != jArray {
		t.Fatalf("%s is not an array", name)
	}
	return v.arr
}

func field(obj jsonValue, key string) (jsonValue, bool) {
	if obj.kind != jObject {
		return jsonValue{}, false
	}
	for _, m := range obj.obj {
		if m.key == key {
			return m.val, true
		}
	}
	return jsonValue{}, false
}

func asStr(t *testing.T, j jsonValue) string {
	t.Helper()
	if j.kind != jStr {
		t.Fatalf("expected string, got kind %d", j.kind)
	}
	return j.str
}

func toHex(b []byte) string { return hex.EncodeToString(b) }

func fromHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex %q: %v", s, err)
	}
	return b
}

// buildInto interprets a build op into encoded bytes — mirrors the Zig generator
// and the other languages' conformance tests.
func buildInto(t *testing.T, w *Writer, op jsonValue) {
	t.Helper()
	if op.kind != jObject || len(op.obj) == 0 {
		t.Fatalf("op must be a one-key object")
	}
	key := op.obj[0].key
	val := op.obj[0].val
	switch key {
	case "nil":
		w.AppendNil()
	case "undef":
		w.AppendUndefined()
	case "bool":
		w.AppendBool(val.kind == jBool && val.boolVal)
	case "int":
		n, err := strconv.ParseInt(asStr(t, val), 10, 64)
		if err != nil {
			t.Fatalf("bad int %q: %v", val.str, err)
		}
		w.AppendInt(n)
	case "float64":
		w.AppendF64(opFloat(t, val))
	case "float32":
		w.AppendF32(float32(opFloat(t, val)))
	case "decimal":
		if err := w.AppendDecimalString(asStr(t, val)); err != nil {
			t.Fatalf("bad decimal %q: %v", val.str, err)
		}
	case "timestamp":
		n, err := strconv.ParseInt(asStr(t, val), 10, 64)
		if err != nil {
			t.Fatalf("bad timestamp %q: %v", val.str, err)
		}
		w.AppendTimestamp(n)
	case "uuid":
		raw := fromHex(t, asStr(t, val))
		if len(raw) != 16 {
			t.Fatalf("uuid must be 16 bytes, got %d", len(raw))
		}
		var u [16]byte
		copy(u[:], raw)
		w.AppendUUID(u)
	case "string":
		w.AppendString(asStr(t, val))
	case "bytes":
		w.AppendBytes(fromHex(t, asStr(t, val)))
	case "array":
		child := NewWriter()
		for _, item := range val.arr {
			buildInto(t, child, item)
		}
		w.AppendArray(child.Bytes())
	case "set":
		elems := make([][]byte, 0, len(val.arr))
		for _, item := range val.arr {
			ep := NewWriter()
			buildInto(t, ep, item)
			// copy: each sub-writer reuses its own buffer, but AppendSet keeps
			// references until it sorts/dedups — distinct writers so safe.
			elems = append(elems, ep.Bytes())
		}
		w.AppendSet(elems)
	case "map":
		entries := make([][2][]byte, 0, len(val.arr))
		for _, pair := range val.arr {
			kp := NewWriter()
			buildInto(t, kp, pair.arr[0])
			vp := NewWriter()
			buildInto(t, vp, pair.arr[1])
			entries = append(entries, [2][]byte{kp.Bytes(), vp.Bytes()})
		}
		w.AppendMap(entries)
	default:
		t.Fatalf("unknown op %q", key)
	}
}

func opFloat(t *testing.T, j jsonValue) float64 {
	t.Helper()
	switch j.kind {
	case jFloat:
		return j.floatV
	case jInt:
		return float64(j.intVal)
	default:
		t.Fatalf("expected number op value, got kind %d", j.kind)
		return 0
	}
}

func buildOne(t *testing.T, op jsonValue) []byte {
	w := NewWriter()
	buildInto(t, w, op)
	return w.Bytes()
}

func TestCorpusHasVectors(t *testing.T) {
	if len(loadCorpus(t, "vectors.json")) == 0 {
		t.Fatal("empty corpus")
	}
}

func TestJSONEncode(t *testing.T) {
	for _, v := range loadCorpus(t, "vectors.json") {
		j, ok := field(v, "json")
		if !ok {
			continue
		}
		want, _ := field(v, "bytes")
		got, err := FromJson(asStr(t, j))
		if err != nil {
			t.Fatalf("FromJson(%s): %v", asStr(t, j), err)
		}
		if toHex(got) != asStr(t, want) {
			t.Errorf("encode %s\n got %s\nwant %s", asStr(t, j), toHex(got), asStr(t, want))
		}
	}
}

func TestJSONDecode(t *testing.T) {
	for _, v := range loadCorpus(t, "vectors.json") {
		j, ok := field(v, "json")
		if !ok {
			continue
		}
		bytesField, _ := field(v, "bytes")
		got, err := ToJson(fromHex(t, asStr(t, bytesField)))
		if err != nil {
			t.Fatalf("ToJson(%s): %v", asStr(t, bytesField), err)
		}
		if got != asStr(t, j) {
			t.Errorf("decode %s\n got %s\nwant %s", asStr(t, bytesField), got, asStr(t, j))
		}
	}
}

func TestBuildEncode(t *testing.T) {
	for _, v := range loadCorpus(t, "vectors.json") {
		op, ok := field(v, "build")
		if !ok {
			continue
		}
		want, _ := field(v, "bytes")
		got := buildOne(t, op)
		if toHex(got) != asStr(t, want) {
			t.Errorf("build %v\n got %s\nwant %s", op, toHex(got), asStr(t, want))
		}
	}
}

func TestBuildTranscode(t *testing.T) {
	for _, v := range loadCorpus(t, "vectors.json") {
		if _, ok := field(v, "build"); !ok {
			continue
		}
		bytesField, _ := field(v, "bytes")
		in := fromHex(t, asStr(t, bytesField))
		got, err := Transcode(in)
		if err != nil {
			t.Fatalf("Transcode(%s): %v", asStr(t, bytesField), err)
		}
		if toHex(got) != asStr(t, bytesField) {
			t.Errorf("transcode %s\n got %s", asStr(t, bytesField), toHex(got))
		}
	}
}

func TestSemanticCorpus(t *testing.T) {
	for _, pr := range loadCorpus(t, "semantic_vectors.json") {
		aField, _ := field(pr, "a")
		bField, _ := field(pr, "b")
		orderField, _ := field(pr, "order")
		if orderField.kind != jInt {
			t.Fatalf("order is not an integer")
		}
		want := orderField.intVal
		got, err := SemanticOrder(fromHex(t, asStr(t, aField)), fromHex(t, asStr(t, bField)))
		if err != nil {
			t.Fatalf("SemanticOrder(%s, %s): %v", asStr(t, aField), asStr(t, bField), err)
		}
		if int64(got) != want {
			t.Errorf("semantic %s <=> %s: got %d want %d", asStr(t, aField), asStr(t, bField), got, want)
		}
	}
}
