// Drives the C++ implementation against the language-neutral contract in
// conformance/vectors.json (generated by the Zig reference). Every vector must
// reproduce in both directions.
#include "struple_json.hpp"

#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

using namespace struple;

static int fails = 0;

static std::string read_file(const char* path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        std::fprintf(stderr, "cannot open %s\n", path);
        std::exit(2);
    }
    std::stringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

static std::string to_hex(const Bytes& b) {
    std::string s;
    char t[3];
    for (auto x : b) {
        std::snprintf(t, sizeof t, "%02x", x);
        s += t;
    }
    return s;
}

static Bytes from_hex(const std::string& h) {
    Bytes b;
    for (size_t i = 0; i + 1 < h.size(); i += 2)
        b.push_back((uint8_t)std::strtol(h.substr(i, 2).c_str(), nullptr, 16));
    return b;
}

static const Json* obj_get(const Json& o, const std::string& key) {
    for (auto& [k, v] : o.entries)
        if (k == key) return &v;
    return nullptr;
}

static double as_f64(const Json& v) {
    return v.kind == Json::Kind::Float ? v.f : std::stod(v.text);
}

static void build_into(Writer& w, const Json& op);

static Bytes build_one(const Json& op) {
    Writer w;
    build_into(w, op);
    return w.take();
}

// Mirrors the Zig generator and the TS/Python/Rust/C conformance tests.
static void build_into(Writer& w, const Json& op) {
    const auto& [key, val] = op.entries[0];
    if (key == "nil") w.append_nil();
    else if (key == "undef") w.append_undefined();
    else if (key == "bool") w.append_bool(val.b);
    else if (key == "int") w.append_int(std::stoll(val.text));
    else if (key == "float64") w.append_f64(as_f64(val));
    else if (key == "float32") w.append_f32(float(as_f64(val)));
    else if (key == "timestamp") w.append_timestamp(std::stoll(val.text));
    else if (key == "string") w.append_string(val.text);
    else if (key == "bytes") w.append_bytes(from_hex(val.text));
    else if (key == "uuid") w.append_uuid(from_hex(val.text));
    else if (key == "array") {
        Writer c;
        for (auto& it : val.items) build_into(c, it);
        w.append_array(c.bytes());
    } else if (key == "set") {
        std::vector<Bytes> elems;
        for (auto& it : val.items) elems.push_back(build_one(it));
        w.append_set(std::move(elems));
    } else if (key == "map") {
        std::vector<std::pair<Bytes, Bytes>> entries;
        for (auto& pair : val.items)
            entries.emplace_back(build_one(pair.items[0]), build_one(pair.items[1]));
        w.append_map(std::move(entries));
    } else {
        throw Error("unknown op " + key);
    }
}

static void expect(const std::string& label, const std::string& got, const std::string& want) {
    if (got != want) {
        std::fprintf(stderr, "FAIL %s: got %s want %s\n", label.c_str(), got.c_str(), want.c_str());
        fails++;
    }
}

int main() {
    std::string text = read_file("../conformance/vectors.json");
    Json root = json_parse(text);

    int je = 0, jd = 0, be = 0, bt = 0;
    for (auto& v : root.items) {
        const std::string& want = obj_get(v, "bytes")->text;
        const Json* json = obj_get(v, "json");
        const Json* build = obj_get(v, "build");
        Bytes bin = from_hex(want);

        if (json) {
            expect(json->text, to_hex(from_json(json->text)), want);
            je++;
            expect("decode " + json->text, to_json(bin), json->text);
            jd++;
        } else if (build) {
            expect("build", to_hex(build_one(*build)), want);
            be++;
            expect("transcode", to_hex(transcode(bin)), want);
            bt++;
        }
    }

    std::printf("test_conformance: json encode %d decode %d | build %d transcode %d | %d failures\n",
                je, jd, be, bt, fails);
    return fails ? 1 : 0;
}
